/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package textgame;

import java.awt.Color;
import javax.swing.JLayeredPane;

/**
 *
 * @author Max
 */
public class GameInterface extends javax.swing.JFrame {

    /**
     * Creates new form GameInterface
     */
    public GameInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doesCharExistPane = new javax.swing.JLayeredPane();
        charExistsCheckLabel1 = new javax.swing.JLabel();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();
        enterCharNamePane = new javax.swing.JLayeredPane();
        charNameLabel = new javax.swing.JLabel();
        charNameField = new javax.swing.JTextField();
        nameTakenLabel = new javax.swing.JLabel();
        menuPane = new javax.swing.JLayeredPane();
        menuOptionsArea = new javax.swing.JTextArea();
        menuChoiceField = new javax.swing.JTextField();
        fightChoicePane = new javax.swing.JLayeredPane();
        fightOptionsArea = new javax.swing.JTextArea();
        fightChoiceField = new javax.swing.JTextField();
        eventScrollPane = new javax.swing.JScrollPane();
        eventOutputArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyGame");

        charExistsCheckLabel1.setText("Do you have an existing character?");

        yesButton.setText("yes");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        noButton.setText("no");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        doesCharExistPane.setLayer(charExistsCheckLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        doesCharExistPane.setLayer(yesButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        doesCharExistPane.setLayer(noButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout doesCharExistPaneLayout = new javax.swing.GroupLayout(doesCharExistPane);
        doesCharExistPane.setLayout(doesCharExistPaneLayout);
        doesCharExistPaneLayout.setHorizontalGroup(
            doesCharExistPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doesCharExistPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(doesCharExistPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(charExistsCheckLabel1)
                    .addGroup(doesCharExistPaneLayout.createSequentialGroup()
                        .addComponent(yesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        doesCharExistPaneLayout.setVerticalGroup(
            doesCharExistPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doesCharExistPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(charExistsCheckLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doesCharExistPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesButton)
                    .addComponent(noButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        charNameLabel.setText("Enter character name");

        charNameField.setToolTipText("-1 to go back");
        charNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charNameFieldActionPerformed(evt);
            }
        });

        nameTakenLabel.setForeground(new java.awt.Color(255, 0, 0));
        nameTakenLabel.setText("Name taken, try again!");

        enterCharNamePane.setLayer(charNameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        enterCharNamePane.setLayer(charNameField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        enterCharNamePane.setLayer(nameTakenLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout enterCharNamePaneLayout = new javax.swing.GroupLayout(enterCharNamePane);
        enterCharNamePane.setLayout(enterCharNamePaneLayout);
        enterCharNamePaneLayout.setHorizontalGroup(
            enterCharNamePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterCharNamePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterCharNamePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTakenLabel)
                    .addGroup(enterCharNamePaneLayout.createSequentialGroup()
                        .addComponent(charNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(charNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        enterCharNamePaneLayout.setVerticalGroup(
            enterCharNamePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterCharNamePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterCharNamePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(charNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(charNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameTakenLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuOptionsArea.setColumns(20);
        menuOptionsArea.setRows(5);
        menuOptionsArea.setText("1: Enter dungeon\n2: Show stats\n3: Save and quit\nChoose an option:");

        menuPane.setLayer(menuOptionsArea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        menuPane.setLayer(menuChoiceField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout menuPaneLayout = new javax.swing.GroupLayout(menuPane);
        menuPane.setLayout(menuPaneLayout);
        menuPaneLayout.setHorizontalGroup(
            menuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuOptionsArea, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuChoiceField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPaneLayout.setVerticalGroup(
            menuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuOptionsArea, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuChoiceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fightOptionsArea.setColumns(20);
        fightOptionsArea.setRows(5);
        fightOptionsArea.setText("1: Attack\n2: Flee\n3: Heal\nChoose an option:");

        eventOutputArea.setColumns(20);
        eventOutputArea.setRows(5);
        eventScrollPane.setViewportView(eventOutputArea);

        fightChoicePane.setLayer(fightOptionsArea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fightChoicePane.setLayer(fightChoiceField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fightChoicePane.setLayer(eventScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout fightChoicePaneLayout = new javax.swing.GroupLayout(fightChoicePane);
        fightChoicePane.setLayout(fightChoicePaneLayout);
        fightChoicePaneLayout.setHorizontalGroup(
            fightChoicePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fightChoicePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fightChoicePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eventScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fightChoicePaneLayout.createSequentialGroup()
                        .addComponent(fightOptionsArea, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fightChoiceField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        fightChoicePaneLayout.setVerticalGroup(
            fightChoicePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fightChoicePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fightChoicePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fightOptionsArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fightChoicePaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fightChoiceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(18, 18, 18)
                .addComponent(eventScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doesCharExistPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterCharNamePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fightChoicePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(doesCharExistPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterCharNamePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fightChoicePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        SwitchPane(enterCharNamePane);
        nameTakenLabel.setVisible(false);
    }//GEN-LAST:event_noButtonActionPerformed

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        SwitchPane(enterCharNamePane);
        nameTakenLabel.setVisible(false);
    }//GEN-LAST:event_yesButtonActionPerformed

    private void charNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charNameFieldActionPerformed
        if(charNameField.getText().length() > 1) {
            SwitchPane(menuPane);
        }
        else {
            if (!nameTakenLabel.isVisible()) {
                nameTakenLabel.setVisible(true);
            }
            else {
                if (nameTakenLabel.getForeground() == Color.red) {
                    nameTakenLabel.setForeground(Color.blue);
                }
                else {
                    nameTakenLabel.setForeground(Color.red);
                }
            }
        }
    }//GEN-LAST:event_charNameFieldActionPerformed

    private void SwitchPane(JLayeredPane p1) {
        this.dispose();
        GameInterface game = new GameInterface();
        game.setContentPane(p1);
        game.repaint();
        game.revalidate();
        game.setVisible(true);
    }

    public JLayeredPane getDoesCharExistsPane() {
        return doesCharExistPane;
    }

    public JLayeredPane getEnterCharNamePane() {
        return enterCharNamePane;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel charExistsCheckLabel1;
    private javax.swing.JTextField charNameField;
    private javax.swing.JLabel charNameLabel;
    private javax.swing.JLayeredPane doesCharExistPane;
    private javax.swing.JLayeredPane enterCharNamePane;
    private javax.swing.JTextArea eventOutputArea;
    private javax.swing.JScrollPane eventScrollPane;
    private javax.swing.JTextField fightChoiceField;
    private javax.swing.JLayeredPane fightChoicePane;
    private javax.swing.JTextArea fightOptionsArea;
    private javax.swing.JTextField menuChoiceField;
    private javax.swing.JTextArea menuOptionsArea;
    private javax.swing.JLayeredPane menuPane;
    private javax.swing.JLabel nameTakenLabel;
    private javax.swing.JButton noButton;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables

    


}
